# Generated by Django 2.2.5 on 2020-05-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_auto_20200427_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codenamessession',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkChat',
                                    verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='codenamesuser',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkChat',
                                    verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='codenamesuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                    verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                    verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='petrovichgames',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkChat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='petrovichgames',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                    verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='petrovichuser',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkChat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='petrovichuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                    verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkChat',
                                    verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gamer',
                                    verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rouletterate',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkChat',
                                    verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='rouletterate',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gamer',
                                    verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='tictactoesession',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='next_tictactoesessions', to='API_VK.VkUser',
                                    verbose_name='Следующий шаг'),
        ),
        migrations.AlterField(
            model_name='tictactoesession',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user1_tictactoesessions', to='API_VK.VkUser',
                                    verbose_name='Пользователь *'),
        ),
        migrations.AlterField(
            model_name='tictactoesession',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user2_tictactoesessions', to='API_VK.VkUser',
                                    verbose_name='Пользователь o'),
        ),
    ]
