# Generated by Django 2.2.13 on 2020-06-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Session',
                                              verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
                ('is_bought', models.BooleanField(default=False, verbose_name='Куплено')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Session',
                                              verbose_name='Сессия')),
                ('tare',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Tare',
                                   verbose_name='Тара')),
                ('user',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.User',
                                   verbose_name='Купил')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Product',
                                              verbose_name='Продукт')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Session',
                                              verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Туса',
                'verbose_name_plural': 'Тусы',
                'ordering': ['id'],
            },
        ),
    ]
