# Generated by Django 2.2.13 on 2020-06-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('amount', models.CharField(blank=True, max_length=10, verbose_name='Количество')),
                ('currency', models.CharField(blank=True, max_length=30, verbose_name='Валюта')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя')),
                ('value', models.CharField(default='', max_length=5000, null=True, verbose_name='Значение')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=20, verbose_name='Команда')),
                ('count_queries', models.IntegerField(default=0, verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'статистику',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Временная зона UTC')),
            ],
            options={
                'verbose_name': 'таймзона',
                'verbose_name_plural': 'таймзоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('synonyms', models.CharField(max_length=300, verbose_name='Похожие названия')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('timezone',
                 models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='service.TimeZone', verbose_name='Временная зона UTC')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['name'],
            },
        ),
    ]
