# Generated by Django 2.2.5 on 2020-04-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('API_VK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('synonyms', models.CharField(max_length=300, verbose_name='Похожие названия')),
                ('timezone', models.CharField(max_length=30, null=True, verbose_name='Временная зона UTC')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lon', models.FloatField(null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Фича')),
            ],
            options={
                'verbose_name': 'ишю',
                'verbose_name_plural': 'Ишюс',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя')),
                ('value', models.CharField(default='', max_length=1000, null=True, verbose_name='Значение')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=20, verbose_name='Команда')),
                ('count_queries', models.IntegerField(default=0, verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'статистику',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('text', models.CharField(default='', max_length=1000, verbose_name='Напоминашка')),
                ('from_chat', models.BooleanField(default=False, verbose_name='Из чата')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='API_VK.VkChat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'оповещение',
                'verbose_name_plural': 'оповещения',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Ссылка')),
                ('image',
                 models.ImageField(blank=True, null=True, upload_to='service/memes/', verbose_name='Изображение')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'мем',
                'verbose_name_plural': 'мемы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='API_VK.VkChat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'счётчик',
                'verbose_name_plural': 'счётчики',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='service/cats/', verbose_name='Изображение')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'кот',
                'verbose_name_plural': 'коты',
            },
        ),
    ]
