# Generated by Django 2.2.5 on 2020-04-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0002_auto_20200405_2312'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('attachment',
                 models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Вложение')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
            ],
        ),
    ]
