# Generated by Django 2.2.5 on 2020-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_audiolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiolist',
            options={'ordering': ['name'], 'verbose_name': 'аудио-список', 'verbose_name_plural': 'аудио-списки'},
        ),
        migrations.AddField(
            model_name='notify',
            name='repeat',
            field=models.BooleanField(default=True, verbose_name='Повторять'),
        ),
    ]
