# Generated by Django 2.2.5 on 2020-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_auto_20200412_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Повторять'),
        ),
    ]
