# Generated by Django 2.2.5 on 2020-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_auto_20200412_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='text_for_filter',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст для поиска'),
        ),
    ]
