# Generated by Django 2.2.5 on 2020-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0005_notify_text_for_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ['text'], 'verbose_name': 'напоминание', 'verbose_name_plural': 'напоминания'},
        ),
        migrations.AlterField(
            model_name='notify',
            name='date',
            field=models.DateTimeField(verbose_name='Дата напоминания'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='text',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст/команда'),
        ),
    ]
