# Generated by Django 2.2.5 on 2020-04-13 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_auto_20200412_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='from_chat',
        ),
    ]
