# Generated by Django 2.2.5 on 2020-04-17 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_remove_notify_from_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ['date'], 'verbose_name': 'напоминание', 'verbose_name_plural': 'напоминания'},
        ),
    ]
