# Generated by Django 2.2.5 on 2020-04-18 18:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0009_notify_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Вложения'),
        ),
    ]
