# Generated by Django 2.2.5 on 2020-04-19 10:15

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0002_auto_20200405_2312'),
        ('service', '0010_auto_20200418_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaterMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата сообщения')),
                ('attachments',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Вложения')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
            ],
        ),
    ]
