# Generated by Django 2.2.5 on 2020-04-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0002_auto_20200405_2312'),
        ('service', '0011_latermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='latermessage',
            name='message_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='message_author_latermessages', to='API_VK.VkUser',
                                    verbose_name='Автор сообщения'),
        ),
        migrations.AlterField(
            model_name='latermessage',
            name='text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст'),
        ),
    ]
