# Generated by Django 2.2.5 on 2020-04-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0013_auto_20200419_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latermessage',
            name='message_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkBot',
                                    verbose_name='Автор сообщения(бот)'),
        ),
    ]
