# Generated by Django 2.2.5 on 2020-04-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0014_auto_20200419_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latermessage',
            options={'ordering': ['-date'], 'verbose_name': 'Потом сообщение',
                     'verbose_name_plural': 'Потом сообщения'},
        ),
        migrations.AlterField(
            model_name='latermessage',
            name='message_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='message_author_latermessages', to='API_VK.VkUser',
                                    verbose_name='Автор сообщения'),
        ),
        migrations.AlterField(
            model_name='latermessage',
            name='message_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkBot', verbose_name='Автор сообщения(бот)'),
        ),
    ]
