# Generated by Django 2.2.5 on 2020-04-24 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0016_donations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
