# Generated by Django 2.2.5 on 2020-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0017_delete_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('amount', models.CharField(blank=True, max_length=10, verbose_name='Количество')),
                ('currency', models.CharField(blank=True, max_length=30, verbose_name='Валюта')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Донаты',
                'verbose_name_plural': 'Донат',
                'ordering': ['-date'],
            },
        ),
    ]
