# Generated by Django 2.2.5 on 2020-04-25 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0018_donations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'ordering': ['-date'], 'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
    ]
