# Generated by Django 2.2.5 on 2020-04-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0019_auto_20200425_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Временная зона UTC')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.TimeZone', verbose_name='Временная зона UTC'),
        ),
    ]
