# Generated by Django 2.2.5 on 2020-04-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0023_auto_20200426_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.TimeZone', verbose_name='Временная зона UTC'),
        ),
    ]
