# Generated by Django 2.2.5 on 2020-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0024_auto_20200426_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['name'], 'verbose_name': 'таймзона', 'verbose_name_plural': 'таймзоны'},
        ),
        migrations.RemoveField(
            model_name='meme',
            name='image',
        ),
        migrations.AddField(
            model_name='meme',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Разрешённый'),
        ),
    ]
