# Generated by Django 2.2.5 on 2020-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0025_auto_20200427_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Разрешённый'),
        ),
    ]
