# Generated by Django 2.2.5 on 2020-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0026_auto_20200427_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'),
                                                        ('doc', 'Документ')], max_length=2),
        ),
    ]
