# Generated by Django 2.2.5 on 2020-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0027_meme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'),
                                                        ('doc', 'Документ')], max_length=5, verbose_name='Тип'),
        ),
    ]
