# Generated by Django 2.2.5 on 2020-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0028_auto_20200427_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Использований'),
        ),
    ]
