# Generated by Django 2.2.5 on 2020-05-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0030_auto_20200501_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                    verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.TimeZone', verbose_name='Временная зона UTC'),
        ),
        migrations.AlterField(
            model_name='latermessage',
            name='message_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkBot', verbose_name='Автор сообщения(бот)'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                    verbose_name='Автор'),
        ),
    ]
