# Generated by Django 2.2.5 on 2020-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0031_auto_20200501_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='to_send',
            field=models.BooleanField(default=True, verbose_name='Разрешённый'),
        ),
    ]
