# Generated by Django 2.2.5 on 2020-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0033_auto_20200504_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='to_send',
            field=models.BooleanField(default=True, verbose_name='Ещё не было'),
        ),
    ]
