# Generated by Django 2.2.5 on 2020-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0034_auto_20200504_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaterMessageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('later_messages', models.ManyToManyField(to='service.LaterMessage', verbose_name='Сообщения')),
            ],
        ),
    ]
