# Generated by Django 2.2.5 on 2020-05-23 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0035_latermessagesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaterMessageSession',
        ),
    ]
