# Generated by Django 2.2.5 on 2020-05-23 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0039_latermessage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latermessage',
            name='author',
        ),
    ]
