# Generated by Django 2.2.5 on 2020-05-23 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0040_remove_latermessage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latermessagesession',
            options={'ordering': ['-date'], 'verbose_name': 'Потом сообщение (сессия)',
                     'verbose_name_plural': 'Потом сообщения (сессия)'},
        ),
    ]
