# Generated by Django 2.2.5 on 2020-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0042_youtubesubscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeSubscribe',
        ),
    ]
