# Generated by Django 2.2.5 on 2020-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0044_youtubesubscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubesubscribe',
            options={'ordering': ['title'], 'verbose_name': 'Подписка ютуба', 'verbose_name_plural': 'Подписки ютуба'},
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memes', models.ManyToManyField(to='service.Meme')),
            ],
        ),
    ]
