# Generated by Django 2.2.5 on 2020-05-28 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0045_auto_20200528_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscope',
            old_name='Memes',
            new_name='memes',
        ),
    ]
