# Generated by Django 2.2.5 on 2020-05-29 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0048_wakeonlanuserdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WakeOnLanUserData',
        ),
    ]
