# Generated by Django 2.2.5 on 2020-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0050_wakeonlanuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.CharField(default='', max_length=5000, null=True, verbose_name='Значение'),
        ),
    ]
