# Generated by Django 2.2.13 on 2020-06-08 21:18

import django.db.models.deletion
from django.db import migrations, models

import apps.API_VK.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=20, verbose_name='ID бота')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VkChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='', max_length=20, verbose_name='ID чата')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='Название')),
                ('need_reaction', models.BooleanField(default=True, verbose_name='Реагировать')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['chat_id'],
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.CharField(max_length=500, null=True, verbose_name='Мужской')),
                ('f1', models.CharField(max_length=500, null=True, verbose_name='Женский')),
                ('n1', models.CharField(max_length=500, null=True, verbose_name='Средний')),
                ('mm', models.CharField(max_length=500, null=True, verbose_name='Множественный мужской')),
                ('fm', models.CharField(max_length=500, null=True, verbose_name='Множественный женский')),
                ('type',
                 models.CharField(choices=[('bad', 'Плохое'), ('good', 'Хорошее')], default='bad', max_length=10,
                                  verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='ID пользователя')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=40, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, default='', max_length=40, verbose_name='Никнейм')),
                ('nickname_real', models.CharField(blank=True, default='', max_length=40, verbose_name='Прозвище')),
                ('gender', models.CharField(blank=True, choices=[('1', 'женский'), ('2', 'мужской'), ('', 'не указан')],
                                            default='', max_length=2, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('chats', models.ManyToManyField(blank=True, to='API_VK.VkChat', verbose_name='Чаты')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='service.City', verbose_name='Город')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='Группы')),
                ('send_notify_to',
                 models.ManyToManyField(blank=True, related_name='_vkuser_send_notify_to_+', to='API_VK.VkUser',
                                        verbose_name='Отправление уведомлений')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.AddField(
            model_name='vkchat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Админ'),
        ),
        migrations.CreateModel(
            name='QuoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('vk_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkChat', verbose_name='Чат')),
                ('vk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkUser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('imei', models.CharField(max_length=20, null=True, verbose_name='IMEI')),
                ('event', models.CharField(choices=[('home', 'дома'), ('work', 'работа'), ('university', 'университет'),
                                                    ('somewhere', 'где-то')], max_length=20, null=True,
                                           verbose_name='Событие')),
                ('msg', models.CharField(max_length=2000, verbose_name='Сообщение')),
                ('success', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                   verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('vk_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkChat', verbose_name='Вк чат')),
                ('vk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkUser', verbose_name='Вк юзер')),
            ],
            options={
                'verbose_name': 'API Пользователь',
                'verbose_name_plural': 'API Пользователи',
            },
        ),
        migrations.CreateModel(
            name='APITempUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('code', models.CharField(default=apps.API_VK.models.random_digits, max_length=6,
                                          verbose_name='Код подтверждения')),
                ('tries', models.IntegerField(default=5, verbose_name='Кол-во попыток')),
                ('vk_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkChat', verbose_name='Вк чат')),
                ('vk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkUser', verbose_name='Вк юзер')),
            ],
            options={
                'verbose_name': 'API Временный пользователь',
                'verbose_name_plural': 'API Временные пользователи',
            },
        ),
    ]
