# Generated by Django 2.2.5 on 2020-04-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('API_VK', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='send_notify_to',
            field=models.ManyToManyField(blank=True, related_name='_vkuser_send_notify_to_+', to='API_VK.VkUser',
                                         verbose_name='Отправление уведомлений'),
        ),
        migrations.AddField(
            model_name='log',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkChat', verbose_name='Вк чат'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Вк юзер'),
        ),
        migrations.AddField(
            model_name='apitempuser',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkChat', verbose_name='Вк чат'),
        ),
        migrations.AddField(
            model_name='apitempuser',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Вк юзер'),
        ),
    ]
