# Generated by Django 2.2.5 on 2020-04-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0002_auto_20200405_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkchat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Админ конфы'),
        ),
    ]
