# Generated by Django 2.2.5 on 2020-04-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0003_vkchat_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebook',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkChat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='quotebook',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Автор'),
        ),
    ]
