# Generated by Django 2.2.5 on 2020-04-26 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0004_auto_20200426_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebook',
            name='peer_id',
        ),
    ]
