# Generated by Django 2.2.5 on 2020-05-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0006_auto_20200426_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitempuser',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkChat', verbose_name='Вк чат'),
        ),
        migrations.AlterField(
            model_name='apitempuser',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkUser', verbose_name='Вк юзер'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkChat', verbose_name='Вк чат'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkUser', verbose_name='Вк юзер'),
        ),
        migrations.AlterField(
            model_name='log',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                    verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quotebook',
            name='vk_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkChat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='quotebook',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkUser', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='vkchat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API_VK.VkUser', verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='service.City', verbose_name='Город'),
        ),
    ]
