# Generated by Django 2.2.5 on 2020-05-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0007_auto_20200501_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_VK.VkUser',
                                    verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='vkchat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='API_VK.VkUser', verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.City', verbose_name='Город'),
        ),
    ]
