# Generated by Django 2.2.5 on 2020-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0008_auto_20200501_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkchat',
            name='need_reaction',
            field=models.BooleanField(default=True, verbose_name='Реагировать'),
        ),
    ]
