# Generated by Django 2.2.5 on 2020-05-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API_VK', '0009_vkchat_need_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'женский'), ('2', 'мужской'), ('', 'не указан')],
                                   default='', max_length=2, verbose_name='Пол'),
        ),
    ]
