# Generated by Django 2.2.13 on 2020-07-04 12:35

import django.db.models.deletion
from django.db import migrations, models

import apps.API_TG.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('API_VK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='ID пользователя')),
                ('vk_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_VK.VkUser',
                                   verbose_name='ВК Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TgTempUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.API_TG.models.random_digits, max_length=6,
                                          verbose_name='Код подтверждения')),
                ('tries', models.IntegerField(default=5, verbose_name='Кол-во попыток')),
                ('tg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_TG.TgUser', verbose_name='Тг юзер')),
                ('vk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='API_VK.VkUser', verbose_name='Вк юзер')),
            ],
        ),
    ]
