# Generated by Django 2.2.13 on 2020-07-04 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('API_TG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgtempuser',
            options={'verbose_name': 'Временный пользователь', 'verbose_name_plural': 'Временные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
